services:

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - mongodb_data:/data/db

    networks:
      - app-network

    healthcheck:
      test:
        - CMD-SHELL
        - >
          mongosh --quiet
          --username "$$MONGO_INITDB_ROOT_USERNAME"
          --password "$$MONGO_INITDB_ROOT_PASSWORD"
          --authenticationDatabase admin
          --eval "db.adminCommand('ping').ok"
          | grep 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  nextjs:
    build: .
    container_name: nextjs-app
    restart: unless-stopped

    ports:
      - "127.0.0.1:3000:3000"

    environment:
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/companydb?authSource=admin

    depends_on:
      mongodb:
        condition: service_healthy

    networks:
      - app-network


volumes:
  mongodb_data:


networks:
  app-network:
    driver: bridge
