name: Deploy Next.js to Ubuntu

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure SSH using private key
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # 3. Install rsync
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      # 4. Sync complete application to Ubuntu server
      - name: Sync application using rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${{ secrets.SERVER_PORT }}" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/instance/

      # 5. Deploy application
      - name: Build and start application
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.SERVER_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            cd /home/ubuntu/instance

            docker build -t instance .

            docker compose up -d 

            

          EOF
